GET_ACCOUNT_WITH_USERNAME_QUERY = \
    SELECT \
        id \
    FROM \
        Account \
    WHERE \
        username = ?
GET_ACCOUNT_WITH_CREDENTIALS_QUERY = \
    SELECT \
        username, \
        password \
    FROM \
        Account \
    WHERE \
        username = ?
CREATE_ACCOUNT_QUERY = \
    INSERT INTO \
        Account (username, password) \
    VALUES \
        (?, ?)
CREATE_STUDYGUIDE_QUERY = \
    INSERT INTO \
        Studyguide (title, description, idAccount) \
    OUTPUT inserted.id \
    VALUES (?, ?, ?)
UPSERT_STUDYGUIDE_STATUS_QUERY = \
    MERGE AccountStudyguideStatus AS target \
    USING \
        (VALUES (?, ?, ?, ?)) AS source (accountId, studyguideId, favorited, downloaded) \
    ON \
        target.idAccount = source.accountId AND \
        target.idStudyguide = source.studyguideId \
    WHEN MATCHED THEN \
        UPDATE SET \
            target.favorited = source.favorited, \
            target.downloaded = source.downloaded \
    WHEN NOT MATCHED THEN \
        INSERT (idAccount, idStudyguide, favorited, downloaded) \
        VALUES (source.accountId, source.studyguideId, source.favorited, source.downloaded);
CREATE_QUESTION_QUERY = \
    INSERT INTO \
        Question (text, idStudyguide) \
    OUTPUT inserted.id \
    VALUES (?, ?)
CREATE_CHOICE_QUERY = \
    INSERT INTO \
        Choice (text, isAnswer, idQuestion) \
    VALUES (?, ?, ?)
GET_STUDYGUIDE_CONTAINING_SUBSTRING_QUERY = \
    WITH loggedInUser AS ( \
        SELECT \
            id, \
            username \
        FROM \
            Account \
        WHERE \
            username = ? \
    ), \
    linkedAccSgInfo AS ( \
        SELECT \
            idStudyguide, \
            favorited, \
            downloaded \
        FROM AccountStudyguideStatus \
            JOIN loggedInUser \
                ON AccountStudyguideStatus.idAccount = loggedInUser.id \
        WHERE \
            idAccount = loggedInUser.id \
    ), \
    uniqueStudyguide AS ( \
        SELECT \
            account.username, \
            studyguide.id, \
            studyguide.title, \
            studyguide.description, \
            linkedInfo.favorited, \
            linkedInfo.downloaded \
        FROM Studyguide studyguide \
            LEFT JOIN Account account \
                ON studyguide.idAccount = account.id \
            LEFT JOIN linkedAccSgInfo linkedInfo \
                ON studyguide.id = linkedInfo.idStudyguide \
        WHERE \
            account.username LIKE ? OR \
            studyguide.title LIKE ? OR \
            studyguide.description LIKE ? \
        ORDER BY \
            studyguide.id \
        OFFSET ? ROWS FETCH NEXT ? ROWS ONLY \
    ) \
    SELECT \
        studyguide.username, \
        studyguide.id AS studyguideId, \
        studyguide.title, \
        studyguide.description, \
        studyguide.favorited, \
        studyguide.downloaded, \
        question.id AS questionId, \
        question.text AS questionText, \
        choice.text AS choiceText, \
        choice.isAnswer AS choiceIsAnswer \
    FROM uniqueStudyguide studyguide \
        LEFT JOIN Question question \
            ON question.idStudyguide = studyguide.id \
        LEFT JOIN Choice choice \
            ON choice.idQuestion = question.id \
    ORDER BY \
            studyguide.title
TRANSFER_STUDYGUIDE_STATS_QUERY = \
    DECLARE @results TABLE ( \
        action NVARCHAR(255), \
        idAccount INT, \
        idStudyguide INT, \
        favorited BIT, \
        downloaded BIT \
    ) \
    MERGE AccountStudyguideStatus AS target \
        USING \
            (VALUES (?, ?)) AS source (fromId, toId) \
        ON \
            target.idStudyguide = source.fromId \
        WHEN MATCHED THEN \
            DELETE \
        OUTPUT \
            $action AS action, \
            deleted.idAccount AS oldIdAccount, \
            source.toId AS newIdStudyguide, \
            deleted.favorited AS oldFavorited, \
            deleted.downloaded AS oldDownloaded \
        INTO \
            @results (action, idAccount, idStudyguide, favorited, downloaded); \
    MERGE AccountStudyguideStatus AS target \
        USING \
            @results AS source \
        ON \
            target.idAccount = source.idAccount AND \
            target.idStudyguide = source.idStudyguide \
        WHEN MATCHED THEN \
            UPDATE SET \
                target.favorited = source.favorited, \
                target.downloaded = source.downloaded \
        WHEN NOT MATCHED THEN \
            INSERT \
                (idAccount, idStudyguide, favorited, downloaded) \
            VALUES \
                (source.idAccount, source.idStudyguide, source.favorited, source.downloaded);
DELETE_STUDYGUIDE_QUERY = \
    DELETE FROM Studyguide \
        WHERE \
            idAccount IN ( \
                SELECT \
                    id \
                FROM Account \
                WHERE \
                    username = ? \
            ) AND \
            id = ?