USERNAME_EXISTS_QUERY = \
    SELECT \
        id \
    FROM \
        Account \
    WHERE \
        username = ?
CORRECT_CREDENTIALS_QUERY = \
    SELECT \
        username, \
        password \
    FROM \
        Account \
    WHERE \
        username = ?
CREATE_ACCOUNT_QUERY = \
    INSERT INTO \
        Account (username, password) \
    VALUES \
        (?, ?)
CREATE_STUDYGUIDE_QUERY = \
    INSERT INTO \
        Studyguide (title, description, idAccount) \
    OUTPUT inserted.id \
    VALUES ( \
        ?, \
        ?, \
        ? \
    )
CREATE_QUESTION_QUERY = \
    INSERT INTO \
        Question (text, idStudyguide) \
    OUTPUT inserted.id \
    VALUES ( \
        ?, \
        ? \
    )
CREATE_CHOICE_QUERY = \
    INSERT INTO \
        Choice (text, isAnswer, idQuestion) \
    VALUES ( \
        ?, \
        ?, \
        ? \
    )
GET_STUDYGUIDE_FROM_ID_QUERY = \
    SELECT \
        account.username, \
        studyguide.id AS studyguideId, \
        studyguide.title, \
        studyguide.description, \
        question.id AS questionId, \
        question.text AS questionText, \
        choice.text AS choiceText, \
        choice.isAnswer AS choiceIsAnswer \
    FROM Studyguide studyguide \
    LEFT JOIN Account account \
        ON studyguide.idAccount = account.id \
    LEFT JOIN Question question \
        ON question.idStudyguide = studyguide.id \
    LEFT JOIN Choice choice \
        ON choice.idQuestion = question.id \
    WHERE studyguide.id = ?
GET_STUDYGUIDE_CONTAINING_SUBSTRING_QUERY = \
    SELECT \
        account.username, \
        studyguide.id AS studyguideId, \
        studyguide.title, \
        studyguide.description, \
        question.id AS questionId, \
        question.text AS questionText, \
        choice.text AS choiceText, \
        choice.isAnswer AS choiceIsAnswer \
    FROM Studyguide studyguide \
    LEFT JOIN Account account \
        ON studyguide.idAccount = account.id \
    LEFT JOIN Question question \
        ON question.idStudyguide = studyguide.id \
    LEFT JOIN Choice choice \
        ON choice.idQuestion = question.id \
    WHERE \
        account.username LIKE ? OR \
        studyguide.title LIKE ? OR \
        studyguide.description LIKE ?
DELETE_STUDYGUIDE_QUERY = \
    DELETE FROM Studyguide \
        WHERE id = ?